### ISSUE TITLE
Can piercing get added to bows?

### ISSUE THREAD

**Issue by schmitzrj** [SmushyTaco/Expanded-Bow-Enchanting#1]
I love that you created this mod and bows get looting! Thank you! I'm using this mod with Legacy Bows (thanks for that as well!), and it shoots so fast that some arrows bounce off of mobs. Would it be possible to add piercing to bows so the arrows go through? Then the player won't take damage from arrows bouncing back against the player when the two mods are used together.

**Comment by SmushyTaco** [comment]
There's a tick delay between how often a mob can be damaged, so the arrows bounce back because of that delay, I don't think piercing would bypass that. Nevertheless, I'll investigate crossbow enchantments on bows for the 1.21 update which is releasing soon.

**Comment by schmitzrj** [comment]
Since Legacy Bows also speeds up crossbows, I tried using one with Piercing III during a raid. I only had one arrow bounce back and hit me when one mob got really close, so I hoped it might work when applied to bows, especially since I missed out on the Looting benefit with the crossbow. Thanks for looking into the possibility!

**Comment by SmushyTaco** [comment]
Support for multishot and piercing has been added for the 1.21 update. Enjoy!
