### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by MosquitoCoding** [SmushyTaco/Expanded-Bow-Enchanting#2]
Hey a friend of mine just encountered this crash
[crash-2024-08-01_20.39.54-client.txt](https://github.com/user-attachments/files/16460787/crash-2024-08-01_20.39.54-client.txt)
She was trying to craft together two bows in an anvil when it crashed. This happened even after rejoining the server and retrying.

I can provide more information if needed but I hope the crash report is enough for now.

**Comment by SmushyTaco** [comment]
The mod is only needed on the server. It isn't needed on the client unless you're in a singleplayer world. So if the mod is on the server just have your friend delete the mod from her client and the crash will be gone. I'll release a fix tomorrow.
