### ISSUE TITLE
Request: Bow with Multishot

### ISSUE THREAD

**Issue by heromedel** [SmushyTaco/Expanded-Bow-Enchanting#5]
I have been trying to find a way to allow players to have a bow with multishot on 1.21.3 (fabric) and cannot find a way to I know I can use commands to create a bow with multishot but if the player attempts to enchant the bow further then is multishot is removed. 

I saw that you have made this mod and the expanded cross bow mod and I thought maybe you could help me or add it to your mod. I think ultimately what would be amazing would be a mod with a config through modmenu where you can choose what enchantments are enabled or not for each weapon. For example disabling Punch on a bow and enabling it on a crossbow. But for now Id just like to enable bows to have multishot.

**Comment by SmushyTaco** [comment]
The mod in its current state is finished and already has multi shot enabled. I'm not really sure what you're even asking me.
